name: "Узнаем доступные модули Qt"

on: [push]

jobs:
  check-qt-modules:
    runs-on: windows-latest
    steps:
      - name: Проверка доступных модулей Qt
        shell: pwsh
        run: |
          # Устанавливаем aqtinstall
          pip install aqtinstall
          
          echo "=== Доступные версии Qt для Windows ==="
          aqt list-qt windows desktop
          
          echo "=== Модули для Qt 6.6.2 ==="
          aqt list-qt windows desktop --modules 6.6.2
          
          echo "=== Модули для Qt 5.15.2 ==="
          aqt list-qt windows desktop --modules 5.15.2
